#include <hipblas.h>

// types
#define cublasStatus_t hipblasStatus_t
#define cublasHandle_t hipblasHandle_t
#define cublasPointerMode_t hipblasPointerMode_t
#define cublasAtomicsMode_t hipblasAtomicsMode_t
#define cuComplex hipblasComplex
#define cuDoubleComplex hipblasDoubleComplex
#define cublasOperation_t  hipblasOperation_t

#define CUBLAS_STATUS_SUCCESS HIPBLAS_STATUS_SUCCESS
#define CUBLAS_STATUS_NOT_INITIALIZED HIPBLAS_STATUS_NOT_INITIALIZED
#define CUBLAS_STATUS_ALLOC_FAILED HIPBLAS_STATUS_ALLOC_FAILED
#define CUBLAS_STATUS_INVALID_VALUE HIPBLAS_STATUS_INVALID_VALUE
#define CUBLAS_STATUS_ARCH_MISMATCH HIPBLAS_STATUS_ARCH_MISMATCH
#define CUBLAS_STATUS_MAPPING_ERROR HIPBLAS_STATUS_MAPPING_ERROR
#define CUBLAS_STATUS_EXECUTION_FAILED HIPBLAS_STATUS_EXECUTION_FAILED
#define CUBLAS_STATUS_INTERNAL_ERROR HIPBLAS_STATUS_INTERNAL_ERROR
#define CUBLAS_STATUS_NOT_SUPPORTED HIPBLAS_STATUS_NOT_SUPPORTED

#define CUBLAS_OP_N HIPBLAS_OP_N
#define CUBLAS_OP_T HIPBLAS_OP_T
#define CUBLAS_OP_C HIPBLAS_OP_C

#define CUBLAS_POINTER_MODE_HOST HIPBLAS_POINTER_MODE_HOST
#define CUBLAS_POINTER_MODE_DEVICE HIPBLAS_POINTER_MODE_DEVICE

#define CUBLAS_FILL_MODE_UPPER HIPBLAS_FILL_MODE_UPPER
#define CUBLAS_FILL_MODE_LOWER HIPBLAS_FILL_MODE_LOWER
#define CUBLAS_FILL_MODE_FULL HIPBLAS_FILL_MODE_FULL

#define CUBLAS_DIAG_NON_UNIT HIPBLAS_DIAG_NON_UNIT
#define CUBLAS_DIAG_UNIT HIPBLAS_DIAG_UNIT

#define CUBLAS_SIDE_LEFT HIPBLAS_SIDE_LEFT
#define CUBLAS_SIDE_RIGHT HIPBLAS_SIDE_RIGHT

#define CUBLAS_ATOMICS_NOT_ALLOWED HIPBLAS_ATOMICS_NOT_ALLOWED
#define CUBLAS_ATOMICS_ALLOWED HIPBLAS_ATOMICS_ALLOWED

// util APIs
#define cublasCreate hipblasCreate
#define cublasDestroy hipblasDestroy
#define cublasSetStream hipblasSetStream
#define cublasGetStream hipblasGetStream
#define cublasSetPointerMode hipblasSetPointerMode
#define cublasGetPointerMode hipblasGetPointerMode
#define cublasSetVector hipblasSetVector
#define cublasGetVector hipblasGetVector
#define cublasSetMatrix hipblasSetMatrix
#define cublasGetMatrix hipblasGetMatrix
#define cublasSetVectorAsync hipblasSetVectorAsync
#define cublasGetVectorAsync hipblasGetVectorAsync
#define cublasSetMatrixAsync hipblasSetMatrixAsync
#define cublasGetMatrixAsync hipblasGetMatrixAsync
#define cublasSetAtomicsMode hipblasSetAtomicsMode
#define cublasGetAtomicsMode hipblasGetAtomicsMode

// Level-1
#define cublasIsamax hipblasIsamax
#define cublasIdamax hipblasIdamax
#define cublasIcamax hipblasIcamax
#define cublasIzamax hipblasIzamax
#define cublasIsamin hipblasIsamin
#define cublasIdamin hipblasIdamin
#define cublasIcamin hipblasIcamin
#define cublasIzamin hipblasIzamin
#define cublasSasum hipblasSasum
#define cublasDasum hipblasDasum
#define cublasScasum hipblasScasum
#define cublasDzasum hipblasDzasum
#define cublasSaxpy hipblasSaxpy
#define cublasCaxpy hipblasCaxpy
#define cublasZaxpy hipblasZaxpy
#define cublasScopy hipblasScopy
#define cublasDcopy hipblasDcopy
#define cublasCcopy hipblasCcopy
#define cublasZcopy hipblasZcopy
#define cublasSdot hipblasSdot
#define hipblasDdot hipblasDdot
#define cublasCdotc hipblasCdotc
#define cublasCdotu hipblasCdotu
#define cublasZdotc hipblasZdotc
#define cublasZdotu hipblasZdotu
#define cublasSnrm2 hipblasSnrm2
#define cublasDnrm2 hipblasDnrm2
#define cublasScnrm2 hipblasScnrm2
#define cublasDznrm2 hipblasDznrm2
#define cublasSrot hipblasSrot
#define cublasDrot hipblasDrot
#define cublasCrot hipblasCrot
#define cublasCsrot hipblasCsrot
#define cublasZrot hipblasZrot
#define cublasZdrot hipblasZdrot
#define cublasSrotg hipblasSrotg
#define cublasDrotg hipblasDrotg
#define cublasCrotg hipblasCrotg
#define cublasZrotg hipblasZrotg
#define cublasSrotm hipblasSrotm
#define cublasDrotm hipblasDrotm
#define cublasSrotmg hipblasSrotmg
#define cublasDrotmg hipblasDrotmg
#define cublasSscal hipblasSscal
#define cublasDscal hipblasDscal
#define cublasCscal hipblasCscal
#define cublasCsscal hipblasCsscal
#define cublasZscal hipblasZscal
#define cublasZdscal hipblasZdscal
#define cublasSswap hipblasSswap
#define cublasDswap hipblasDswap
#define cublasCswap hipblasCswap
#define cublasZswap hipblasZswap

// level-2
#define cublasSgbmv hipblasSgbmv
#define cublasDgbmv hipblasDgbmv
#define cublasCgbmv hipblasCgbmv
#define cublasZgbmv hipblasZgbmv
#define cublasSgemv hipblasSgemv
#define cublasDgemv hipblasDgemv
#define cublasCgemv hipblasCgemv
#define cublasZgemv hipblasZgemv
#define cublasSger hipblasSger
#define cublasDger hipblasDger
#define cublasCgeru hipblasCgeru
#define cublasCgerc hipblasCgerc
#define cublasZgeru hipblasZgeru
#define cublasZgerc hipblasZgerc
#define cublasSsbmv hipblasSsbmv
#define cublasDsbmv hipblasDsbmv
#define cublasSspmv hipblasSspmv
#define cublasDspmv hipblasDspmv
#define cublasSspr hipblasSspr
#define cublasDspr hipblasDspr
#define cublasSspr2 hipblasSspr2
#define cublasDspr2 hipblasDspr2
#define cublasSsymv hipblasSsymv
#define cublasDsymv hipblasDsymv
#define cublasCsymv hipblasCsymv
#define cublasZsymv hipblasZsymv
#define cublasSsyr hipblasSsyr
#define cublasDsyr hipblasDsyr
#define cublasCsyr hipblasCsyr
#define cublasZsyr hipblasZsyr
#define cublasSsyr2 hipblasSsyr2
#define cublasDsyr2 hipblasDsyr2
#define cublasCsyr2 hipblasCsyr2
#define cublasZsyr2 hipblasZsyr2
#define cublasStbmv hipblasStbmv
#define cublasDtbmv hipblasDtbmv
#define cublasCtbmv hipblasCtbmv
#define cublasZtbmv hipblasZtbmv
#define cublasStbsv hipblasStbsv
#define cublasDtbsv hipblasDtbsv
#define cublasCtbsv hipblasCtbsv
#define cublasZtbsv hipblasZtbsv
#define cublasStpmv hipblasStpmv
#define cublasDtpmv hipblasDtpmv
#define cublasCtpmv hipblasCtpmv
#define cublasZtpmv hipblasZtpmv
#define cublasStpsv hipblasStpsv
#define cublasDtpsv hipblasDtpsv
#define cublasCtpsv hipblasCtpsv
#define cublasZtpsv hipblasZtpsv
#define cublasStrmv hipblasStrmv
#define cublasDtrmv hipblasDtrmv
#define cublasCtrmv hipblasCtrmv
#define cublasZtrmv hipblasZtrmv
#define cublasStrsv hipblasStrsv
#define cublasDtrsv hipblasDtrsv
#define cublasCtrsv hipblasCtrsv
#define cublasZtrsv hipblasZtrsv
#define cublasChemv hipblasChemv
#define cublasZhemv hipblasZhemv
#define cublasChbmv hipblasChbmv
#define cublasZhbmv hipblasZhbmv
#define cublasChpmv hipblasChpmv
#define cublasZhpmv hipblasZhpmv
#define cublasCher hipblasCher
#define cublasZher hipblasZher
#define cublasCher2 hipblasCher2
#define cublasZher2 hipblasZher2
#define cublasChpr hipblasChpr
#define cublasZhpr hipblasZhpr
#define cublasChpr2 hipblasChpr2
#define cublasZhpr2 hipblasZhpr2
// level-3
//#define cublasHgemm hipblasHgemm
#define cublasSgemm hipblasSgemm
#define cublasDgemm hipblasDgemm
#define cublasCgemm hipblasCgemm
#define cublasZgemm hipblasZgemm
#define cublasSsymm hipblasSsymm
#define cublasDsymm hipblasDsymm
#define cublasCsymm hipblasCsymm
#define cublasZsymm hipblasZsymm
#define cublasSsyrk hipblasSsyrk
#define cublasDsyrk hipblasDsyrk
#define cublasCsyrk hipblasCsyrk
#define cublasZsyrk hipblasZsyrk
#define cublasSsyr2k hipblasSsyr2k
#define cublasDsyr2k hipblasDsyr2k
#define cublasCsyr2k hipblasCsyr2k
#define cublasZsyr2k hipblasZsyr2k
#define cublasSsyrkx hipblasSsyrkx
#define cublasDsyrkx hipblasDsyrkx
#define cublasCsyrkx hipblasCsyrkx
#define cublasZsyrkx hipblasZsyrkx
#define cublasStrmm hipblasStrmm
#define cublasDtrmm hipblasDtrmm
#define cublasCtrmm hipblasCtrmm
#define cublasZtrmm hipblasZtrmm
#define cublasStrsm hipblasStrsm
#define cublasDtrsm hipblasDtrsm
#define cublasCtrsm hipblasCtrsm
#define cublasZtrsm hipblasZtrsm
#define cublasChemm hipblasChemm
#define cublasZhemm hipblasZhemm
#define cublasCherk hipblasCherk
#define cublasZherk hipblasZherk
#define cublasCher2k hipblasCher2k
#define cublasZher2k hipblasZher2k
#define cublasCherkx hipblasCherkx
#define cublasZherkx hipblasZherkx